# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sufficientStatistics <- function(X_, Y_, theta_, options_) {
    .Call('_SparsePosterior_sufficientStatistics', PACKAGE = 'SparsePosterior', X_, Y_, theta_, options_)
}

xtyUpdate <- function(X_, Y_, theta_, result_, options_) {
    .Call('_SparsePosterior_xtyUpdate', PACKAGE = 'SparsePosterior', X_, Y_, theta_, result_, options_)
}

W2penalized <- function(X_, Y_, theta_, family_, penalty_, groups_, unique_groups_, group_weights_, lambda_, nlambda_, lmin_ratio_, alpha_, gamma_, tau_, scale_factor_, penalty_factor_, opts_) {
    .Call('_SparsePosterior_W2penalized', PACKAGE = 'SparsePosterior', X_, Y_, theta_, family_, penalty_, groups_, unique_groups_, group_weights_, lambda_, nlambda_, lmin_ratio_, alpha_, gamma_, tau_, scale_factor_, penalty_factor_, opts_)
}

cost_calculation_ <- function(A_, B_, p) {
    .Call('_SparsePosterior_cost_calculation_', PACKAGE = 'SparsePosterior', A_, B_, p)
}

pbClean <- function() {
    invisible(.Call('_SparsePosterior_pbClean', PACKAGE = 'SparsePosterior'))
}

test <- function() {
    invisible(.Call('_SparsePosterior_test', PACKAGE = 'SparsePosterior'))
}

selVarMeanGen <- function(X_, theta_, beta_) {
    .Call('_SparsePosterior_selVarMeanGen', PACKAGE = 'SparsePosterior', X_, theta_, beta_)
}

sinkhorn_ <- function(p_, q_, cost_matrix_, epsilon, niterations) {
    .Call('_SparsePosterior_sinkhorn_', PACKAGE = 'SparsePosterior', p_, q_, cost_matrix_, epsilon, niterations)
}

transport_C_ <- function(mass_a_, mass_b_, cost_matrix_, method_, epsilon_, niter_) {
    .Call('_SparsePosterior_transport_C_', PACKAGE = 'SparsePosterior', mass_a_, mass_b_, cost_matrix_, method_, epsilon_, niter_)
}

transport_ <- function(A_, B_, p, ground_p, method_, a_sort, epsilon_ = 0.0, niter_ = 0L) {
    .Call('_SparsePosterior_transport_', PACKAGE = 'SparsePosterior', A_, B_, p, ground_p, method_, a_sort, epsilon_, niter_)
}

wasserstein_ <- function(mass_, cost_, p, from_, to_) {
    .Call('_SparsePosterior_wasserstein_', PACKAGE = 'SparsePosterior', mass_, cost_, p, from_, to_)
}

wasserstein_p_iid_ <- function(X_, Y_, p) {
    .Call('_SparsePosterior_wasserstein_p_iid_', PACKAGE = 'SparsePosterior', X_, Y_, p)
}

wasserstein_p_iid_p_ <- function(X_, Y_, p) {
    .Call('_SparsePosterior_wasserstein_p_iid_p_', PACKAGE = 'SparsePosterior', X_, Y_, p)
}

